//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareeriaIOTSensorControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commands
    {
        public int Id_Command { get; set; }
        public int DeviceId { get; set; }
        public string Command { get; set; }
        public Nullable<bool> Executed { get; set; }
    }
}
