//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareeriaIOTSensorControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class measurements
    {
        public int id { get; set; }
        public Nullable<int> sender { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<double> value { get; set; }
    }
}
